#!/bin/bash
SCRIPT_ABS_FILENAME=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "${BASH_SOURCE[0]}"`
SCRIPT_DIR=`dirname "$SCRIPT_ABS_FILENAME"`



(return 0 2>/dev/null) && sourced=1 || sourced=0
#echo $sourced


function do_it
{
		
	if [ $sourced -eq 0 ]
	then
	    echo Please, source this script.
	    return 1
	fi
		
	
	mkdir -p ./tools
	if [ -z "$HOME_URL" ]
	then
	  echo define HOME_URL
	else
	  rsync -a --out-format='%i  - %n  - %M' --delete --exclude=/private --exclude=/DerivedData --delete-excluded rsync://$HOME_URL:2220/root/tools/ ./tools/
	fi
	
	
	source "$SCRIPT_DIR"/../scripts/setup_env
	
	
}

do_it "$@"
