#!/bin/bash
SCRIPT_ABS_FILENAME=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "${BASH_SOURCE[0]}"`
SCRIPT_DIR=`dirname "$SCRIPT_ABS_FILENAME"`

echo -L../lib/lib_osx.11/icu4c/64.2/dylib \
     -L../lib/lib_osx.11/openssl/1.0.2r/dylib \
     -lcrypto_ -lz -lbz2 \
     -isysroot /JiefLand/5.Devel/Thunderbird/MacOSX10.11.sdk -framework Cocoa -framework DiskArbitration -framework IOKit



