#!/bin/bash
SCRIPT_ABS_FILENAME=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "${BASH_SOURCE[0]}"`
SCRIPT_DIR=`dirname "$SCRIPT_ABS_FILENAME"`

#echo `pwd`

me=`basename "$0"`
#echo me=$me

name="${me##*-}"
#echo name=$name

prefix=${me%-$name}
#echo prefix=$prefix

source "$SCRIPT_DIR"/"$prefix"-path "g++" #we use g++ as a linker, so let's ignore $name
ps_dir="$SCRIPT_DIR"/../eclipse_compilation_project_specific


cmdArgs=()
cmdArgs=( "$bin_path"  $("$ps_dir"/"$prefix"-ldflags) "$@"  $("$ps_dir"/"$prefix"-ldflags-post) )

echo "${cmdArgs[@]}"

exec "${cmdArgs[@]}"
